---
title: "collaborator-analysis"
author: "Danica Linda Cantarero"
format: html
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
#| message: false
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

```{r}
lobster_traps <- read_csv(here("data/Lobster_Trap_Counts_All_Years_20210519.csv"))

colnames(lobster_traps)

head(lobster_traps)

summary(lobster_traps)



View(lobster_traps)
```


### missing values to na
```{r}
# Q1
unique(lobster_traps$TRAPS)

lobster_traps <- lobster_traps %>% 
    mutate(TRAPS = na_if(TRAPS, -99999))

unique(lobster_traps$TRAPS)
```

### filter() practice


```{r} 
# Q2
no_napl <- lobster_traps %>% 
  filter(SITE != "NAPL")

# View(no_napl)
unique(no_napl$SITE)
```

```{r}
#Q3
traps_carp_20 <- lobster_traps %>% 
  filter(SITE == "CARP" & TRAPS > 20)

#View(traps_carp_20)
#summary(traps_carp_20)

```
```{r}
#Q4
max_comm_traps <- lobster_traps %>% 
  group_by(SITE, MONTH) %>% 
  summarise(max_traps = max(TRAPS, na.rm = TRUE))
```

## Exercise: Data Visualization

```{r}
ggplot(lobster_traps, aes(TRAPS)) +
  geom_histogram() +
  facet_wrap(~YEAR) + theme_bw()
```


